/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenueSlugRouteImport } from './routes/venue.$slug'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as BookingSlugRouteImport } from './routes/booking.$slug'

const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueSlugRoute = VenueSlugRouteImport.update({
  id: '/venue/$slug',
  path: '/venue/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BookingsRoute,
} as any)
const BookingSlugRoute = BookingSlugRouteImport.update({
  id: '/booking/$slug',
  path: '/booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/venue/$slug': typeof VenueSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/venue/$slug': typeof VenueSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/venue/$slug': typeof VenueSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/marketplace'
    | '/booking/$slug'
    | '/bookings/$id'
    | '/business/$slug'
    | '/venue/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/marketplace'
    | '/booking/$slug'
    | '/bookings/$id'
    | '/business/$slug'
    | '/venue/$slug'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/marketplace'
    | '/booking/$slug'
    | '/bookings/$id'
    | '/business/$slug'
    | '/venue/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  BookingSlugRoute: typeof BookingSlugRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
  VenueSlugRoute: typeof VenueSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$slug': {
      id: '/venue/$slug'
      path: '/venue/$slug'
      fullPath: '/venue/$slug'
      preLoaderRoute: typeof VenueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/booking/$slug': {
      id: '/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/booking/$slug'
      preLoaderRoute: typeof BookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookingsRouteChildren {
  BookingsIdRoute: typeof BookingsIdRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsIdRoute: BookingsIdRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  BookingSlugRoute: BookingSlugRoute,
  BusinessSlugRoute: BusinessSlugRoute,
  VenueSlugRoute: VenueSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
